server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: medilaboPatient
        uri: http://localhost:8081/
        predicates:
        - Path=/patients/**
        
      - id: medilaboFront
        uri: http://localhost:8082/
        predicates:
        - Path=/display/**
        
      - id: medilaboNotes
        uri: http://localhost:8083/
        predicates:
        - Path=/notes/**
        
      - id: medilaboDiag
        uri: http://localhost:8084/
        predicates:
        - Path=/diag/**